CREATE TABLE JSP_MEMBER (
	MID VARCHAR2(20) PRIMARY KEY
	, PASSWORD VARCHAR2(20) NOT NULL
	, NAME VARCHAR2(30) NOT NULL
	, ROLE VARCHAR2(10) DEFAULT 'USER'
);

SELECT * FROM JSP_MEMBER;

DROP TABLE JSP_MEMBER;

INSERT INTO JSP_MEMBER(MID, PASSWORD, NAME, ROLE) VALUES('admin', '1234', '관리자', 'ADMIN');