CREATE TABLE JSP_PRODUCT (
	NUM NUMBER PRIMARY KEY
	, NAME VARCHAR2(50) NOT NULL
	, DETAILS VARCHAR2(100)
	, PRICE NUMBER
	, CNT NUMBER
	, SELLER VARCHAR2(20) NOT NULL
	, CONSTRAINT FK_JSP_SELLER FOREIGN KEY(SELLER) REFERENCES MEMBER(MID) ON DELETE CASCADE
);

SELECT * FROM JSP_PRODUCT;

DROP TABLE JSP_PRODUCT;

DELETE FROM JSP_PRODUCT p ;

INSERT INTO JSP_PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM JSP_PRODUCT), '사이다', '톡쏘는 칠성사이다', 1200, 5, 'admin');
INSERT INTO JSP_PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM JSP_PRODUCT), '콜라', '톡쏘는 코카콜라', 1300, 2, 'admin');
INSERT INTO JSP_PRODUCT 
VALUES((SELECT NVL(MAX(NUM)+1,0) FROM JSP_PRODUCT), '망고 스무디', '달달한 망고 스무디', 3000, 0, 'admin');
